/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Glueops",
  "tagline": "Dataops and Devops platform",
  "url": "https://glueops.dev",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "images/glueops.png",
  "organizationName": "Glueops",
  "projectName": "website",
  "deploymentBranch": "master",
  "trailingSlash": false,
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "plugins": [],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/workspace/glueops-dev/sidebars.js",
          "editUrl": "https://github.com/GlueOps/glueops-dev",
          "sidebarCollapsed": false
        },
        "theme": {
          "customCss": [
            "/workspace/glueops-dev/src/css/custom.css",
            "/workspace/glueops-dev/src/css/helpers.css"
          ]
        },
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.5,
          "ignorePatterns": [
            "/tags/**"
          ],
          "filename": "sitemap.xml"
        }
      }
    ]
  ],
  "themeConfig": {
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "metadata": [
      {
        "name": "keywords",
        "content": "devops, dataops, gitops, workflow, glueops,"
      },
      {
        "name": "description",
        "content": "GlueOps simplifies and optimizes your business’s DevOps and DataOps operations, allowing for efficient management and operation."
      },
      {
        "name": "og:image",
        "content": "https://glueops.dev/images/glueops.png"
      }
    ],
    "navbar": {
      "title": "Glueops",
      "logo": {
        "alt": "Glueops Logo",
        "src": "images/glueops.png",
        "srcDark": "images/glueops.png"
      },
      "items": [
        {
          "type": "doc",
          "docId": "introduction",
          "position": "left",
          "label": "Docs"
        },
        {
          "href": "https://aws.amazon.com/marketplace/pp/prodview-mfwjl2qdvhaes?sr=0-1&ref_=beagle&applicationId=AWSMPContessa",
          "aria-label": "Purchase DataOps on Amazon Marketplace",
          "position": "right",
          "title": "Purchase DataOps on Amazon Marketplace",
          "label": "Purchase DataOps on Amazon Marketplace"
        },
        {
          "href": "https://aws.amazon.com/marketplace/pp/prodview-soaz2d3nlms6k?sr=0-2&ref_=beagle&applicationId=AWSMPContessa",
          "aria-label": "Purchase DevOps on Amazon Marketplace",
          "position": "right",
          "title": "Purchase DevOps on Amazon Marketplace",
          "label": "Purchase DevOps on Amazon Marketplace"
        },
        {
          "href": "https://github.com/GlueOps/glueops-dev",
          "className": "header-github-link",
          "aria-label": "GitHub repository",
          "position": "right",
          "title": "Glueops on Github"
        }
      ],
      "hideOnScroll": true
    },
    "footer": {
      "links": [
        {
          "title": "Address",
          "items": [
            {
              "html": "\n                    <p>\n                    GlueOps, LLC<br>\n                    35 N Franklin Ave<br>\n                    Ste 687 2062<br>\n                    Pinedale, WY 82941\n                    </p>\n                  "
            }
          ]
        },
        {
          "title": "Resources",
          "items": [
            {
              "label": "Docs",
              "to": "#"
            }
          ]
        }
      ],
      "copyright": "Copyright Glueops.",
      "style": "light"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
